
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile.n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - ${DJANGO_PROJECT_PATH}:/django_project
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=n8n-nodes-sqlite
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=true
      # --- Es buena práctica definir explícitamente la DB ---
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      # --- Opcional: Clave API para Qdrant (ver servicio qdrant) ---
      # - N8N_CRED_QDRANT_API_DEFAULT_TYPE=qdrantApi
      # - N8N_CRED_QDRANT_API_DEFAULT_NAME=My Qdrant
      # - N8N_CRED_QDRANT_API_DEFAULT_DATA_apiKey=my_secret_key
      # - N8N_CRED_QDRANT_API_DEFAULT_DATA_url=http://qdrant:6333
    depends_on:
      - postgres
      - qdrant  # <-- Añadido
      - ollama  # <-- Añadido

  n8n-import:
    image: n8nio/n8n:latest
    container_name: n8n-import
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_storage:/home/node/.n8n
    command: ["n8n", "import:workflow", "--separate-tasks"]
    depends_on: # <-- Buena práctica añadir esto
      - n8n

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- NUEVOS SERVICIOS AÑADIDOS ---

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # Puerto API REST
      - "6334:6334" # Puerto gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    # Opcional: Descomenta esto si quieres usar una API Key
    # environment:
    #   - QDRANT__SERVICE__API_KEY=my_secret_key

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    # Opcional: Descomenta el bloque 'deploy' si tienes una GPU NVIDIA
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  n8n_storage:
  postgres_data:
  qdrant_storage: # <-- Añadido
  ollama_storage: # <-- Añadido